DATASET:
  NAME: "red_globe_2021_07-27_09-06"
  ANNOTATIONS_PATH_TRAIN: "/home/bertoglio/data/red_globe_2021_07-27_09-06_split/annotations/red_globe_2021_07-27_09-06_train.json"
  ANNOTATIONS_PATH_TEST: "/home/bertoglio/data/red_globe_2021_07-27_09-06_split/annotations/red_globe_2021_07-27_09-06_test.json"
  IMAGES_PATH_TRAIN: "/home/bertoglio/data/red_globe_2021_07-27_09-06_split/images_train/"
  IMAGES_PATH_TEST: "/home/bertoglio/data/red_globe_2021_07-27_09-06_split/images_test/"