DATASET:
  NAME: "red_globe_2021_07-27_09-06"
  ANNOTATIONS_PATH_TRAIN: "/home/bertoglio/red_globe_2021_07-27_09-06_train_val_test/annotations/annotations_train.json"
  ANNOTATIONS_PATH_TEST: "/home/bertoglio/red_globe_2021_07-27_09-06_train_val_test/annotations/annotations_val.json"
  IMAGES_PATH_TRAIN: "/home/bertoglio/red_globe_2021_07-27_09-06_train_val_test/train/"
  IMAGES_PATH_TEST: "/home/bertoglio/red_globe_2021_07-27_09-06_train_val_test/val/"
  # NAME: "wgisd"
  # ANNOTATIONS_PATH_TRAIN: "/home/bertoglio/wgisd_split/train/annotations.json"
  # ANNOTATIONS_PATH_TEST: "/home/bertoglio/wgisd_split/test/annotations.json"
  # IMAGES_PATH_TRAIN: "/home/bertoglio/wgisd_split/train/images/"
  # IMAGES_PATH_TEST: "/home/bertoglio/wgisd_split/test/images/"