_BASE_: "red_globe_2021_07-27_09-06_train_cfg.yaml"
MODEL:
  WEIGHTS: "../weights/GRAPE-172/model_final.pth"
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.9       # Minimum score threshold (assuming scores in a [0, 1] range)
INPUT:
  MIN_SIZE_TEST: 0                # Set to zero to disable resize in testing
DATASETS:
  TEST: ("red_globe_2022_90deg_TEST",)
